import type { Product, Category, User, Order, Review, Coupon, DashboardStats } from './types'

// Categories
export const categories: Category[] = [
  {
    id: 'cat-1',
    name: 'Electronics',
    slug: 'electronics',
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400',
    subcategories: [
      { id: 'sub-1', name: 'Smartphones', slug: 'smartphones' },
      { id: 'sub-2', name: 'Laptops', slug: 'laptops' },
      { id: 'sub-3', name: 'Tablets', slug: 'tablets' },
      { id: 'sub-4', name: 'Accessories', slug: 'accessories' },
    ],
  },
  {
    id: 'cat-2',
    name: 'Fashion',
    slug: 'fashion',
    image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=400',
    subcategories: [
      { id: 'sub-5', name: 'Men', slug: 'men' },
      { id: 'sub-6', name: 'Women', slug: 'women' },
      { id: 'sub-7', name: 'Kids', slug: 'kids' },
      { id: 'sub-8', name: 'Footwear', slug: 'footwear' },
    ],
  },
  {
    id: 'cat-3',
    name: 'Home & Kitchen',
    slug: 'home-kitchen',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400',
    subcategories: [
      { id: 'sub-9', name: 'Furniture', slug: 'furniture' },
      { id: 'sub-10', name: 'Kitchen Appliances', slug: 'kitchen-appliances' },
      { id: 'sub-11', name: 'Home Decor', slug: 'home-decor' },
      { id: 'sub-12', name: 'Bedding', slug: 'bedding' },
    ],
  },
  {
    id: 'cat-4',
    name: 'Beauty & Health',
    slug: 'beauty-health',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400',
    subcategories: [
      { id: 'sub-13', name: 'Skincare', slug: 'skincare' },
      { id: 'sub-14', name: 'Makeup', slug: 'makeup' },
      { id: 'sub-15', name: 'Haircare', slug: 'haircare' },
      { id: 'sub-16', name: 'Health Devices', slug: 'health-devices' },
    ],
  },
  {
    id: 'cat-5',
    name: 'Sports & Fitness',
    slug: 'sports-fitness',
    image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=400',
    subcategories: [
      { id: 'sub-17', name: 'Gym Equipment', slug: 'gym-equipment' },
      { id: 'sub-18', name: 'Sports Gear', slug: 'sports-gear' },
      { id: 'sub-19', name: 'Fitness Trackers', slug: 'fitness-trackers' },
      { id: 'sub-20', name: 'Outdoor', slug: 'outdoor' },
    ],
  },
  {
    id: 'cat-6',
    name: 'Books & Stationery',
    slug: 'books-stationery',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400',
    subcategories: [
      { id: 'sub-21', name: 'Fiction', slug: 'fiction' },
      { id: 'sub-22', name: 'Non-Fiction', slug: 'non-fiction' },
      { id: 'sub-23', name: 'Academic', slug: 'academic' },
      { id: 'sub-24', name: 'Office Supplies', slug: 'office-supplies' },
    ],
  },
]

// Products
export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'iPhone 15 Pro Max 256GB - Natural Titanium',
    slug: 'iphone-15-pro-max-256gb',
    description: 'The most powerful iPhone ever with A17 Pro chip, titanium design, and advanced camera system. Features a 6.7-inch Super Retina XDR display with ProMotion technology.',
    price: 159900,
    originalPrice: 179900,
    discount: 11,
    images: [
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600',
      'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=600',
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600',
    ],
    category: 'Electronics',
    subcategory: 'Smartphones',
    brand: 'Apple',
    rating: 4.8,
    reviewCount: 2547,
    stock: 45,
    specifications: {
      'Display': '6.7-inch Super Retina XDR',
      'Processor': 'A17 Pro Chip',
      'RAM': '8GB',
      'Storage': '256GB',
      'Camera': '48MP + 12MP + 12MP',
      'Battery': '4422mAh',
      'OS': 'iOS 17',
    },
    features: [
      'Titanium design with textured matte glass back',
      'Action button for quick access',
      '5x optical zoom with telephoto camera',
      'USB-C with USB 3 speeds',
    ],
    tags: ['bestseller', 'premium'],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-20T15:30:00Z',
  },
  {
    id: 'prod-2',
    name: 'Samsung Galaxy S24 Ultra 512GB - Titanium Gray',
    slug: 'samsung-galaxy-s24-ultra-512gb',
    description: 'Experience the ultimate Galaxy with AI-powered features, S Pen integration, and stunning 200MP camera. Built with titanium for durability.',
    price: 134999,
    originalPrice: 149999,
    discount: 10,
    images: [
      'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600',
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600',
    ],
    category: 'Electronics',
    subcategory: 'Smartphones',
    brand: 'Samsung',
    rating: 4.7,
    reviewCount: 1823,
    stock: 32,
    specifications: {
      'Display': '6.8-inch Dynamic AMOLED 2X',
      'Processor': 'Snapdragon 8 Gen 3',
      'RAM': '12GB',
      'Storage': '512GB',
      'Camera': '200MP + 50MP + 12MP + 10MP',
      'Battery': '5000mAh',
      'OS': 'Android 14',
    },
    features: [
      'Galaxy AI for smart assistance',
      'S Pen included',
      '200MP main camera with AI zoom',
      'Titanium frame',
    ],
    tags: ['trending', 'premium'],
    createdAt: '2024-01-18T10:00:00Z',
    updatedAt: '2024-01-22T12:00:00Z',
  },
  {
    id: 'prod-3',
    name: 'MacBook Pro 14" M3 Pro - Space Black',
    slug: 'macbook-pro-14-m3-pro',
    description: 'Supercharged by M3 Pro chip for exceptional performance. Beautiful Liquid Retina XDR display with extreme dynamic range.',
    price: 199900,
    originalPrice: 219900,
    discount: 9,
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600',
      'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=600',
    ],
    category: 'Electronics',
    subcategory: 'Laptops',
    brand: 'Apple',
    rating: 4.9,
    reviewCount: 956,
    stock: 18,
    specifications: {
      'Display': '14.2-inch Liquid Retina XDR',
      'Processor': 'Apple M3 Pro',
      'RAM': '18GB Unified Memory',
      'Storage': '512GB SSD',
      'Battery': 'Up to 17 hours',
      'Weight': '1.55 kg',
    },
    features: [
      'M3 Pro chip with 11-core CPU',
      '14-core GPU',
      'MagSafe 3 charging',
      'HDMI, SDXC, and Thunderbolt 4 ports',
    ],
    tags: ['premium', 'bestseller'],
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-25T10:00:00Z',
  },
  {
    id: 'prod-4',
    name: 'Sony WH-1000XM5 Wireless Headphones - Black',
    slug: 'sony-wh-1000xm5',
    description: 'Industry-leading noise cancellation with exceptional sound quality. Perfect for music, calls, and focus.',
    price: 29990,
    originalPrice: 34990,
    discount: 14,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600',
    ],
    category: 'Electronics',
    subcategory: 'Accessories',
    brand: 'Sony',
    rating: 4.6,
    reviewCount: 3421,
    stock: 156,
    specifications: {
      'Driver': '30mm',
      'Battery Life': '30 hours',
      'Noise Cancellation': 'Industry-leading',
      'Connectivity': 'Bluetooth 5.2',
      'Weight': '250g',
    },
    features: [
      'Auto NC Optimizer',
      'Speak-to-Chat',
      'Multipoint connection',
      '30-hour battery life',
    ],
    tags: ['bestseller'],
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'prod-5',
    name: 'Nike Air Max 270 - Triple Black',
    slug: 'nike-air-max-270-black',
    description: 'The Nike Air Max 270 features the largest Air unit yet for a super-soft ride. Inspired by 1990s running shoes.',
    price: 13995,
    originalPrice: 15995,
    discount: 13,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600',
      'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=600',
    ],
    category: 'Fashion',
    subcategory: 'Footwear',
    brand: 'Nike',
    rating: 4.5,
    reviewCount: 2187,
    stock: 89,
    specifications: {
      'Material': 'Mesh upper',
      'Sole': 'Air Max unit',
      'Closure': 'Lace-up',
      'Style': 'Lifestyle/Running',
    },
    features: [
      'Largest heel Air unit',
      'Breathable mesh',
      'Foam midsole',
      'Rubber outsole',
    ],
    tags: ['trending'],
    createdAt: '2024-01-08T10:00:00Z',
    updatedAt: '2024-01-18T10:00:00Z',
  },
  {
    id: 'prod-6',
    name: 'Dyson V15 Detect Absolute Vacuum',
    slug: 'dyson-v15-detect-absolute',
    description: 'The most powerful Dyson cordless vacuum with laser dust detection and advanced filtration.',
    price: 62900,
    originalPrice: 72900,
    discount: 14,
    images: [
      'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600',
    ],
    category: 'Home & Kitchen',
    subcategory: 'Kitchen Appliances',
    brand: 'Dyson',
    rating: 4.7,
    reviewCount: 876,
    stock: 23,
    specifications: {
      'Suction Power': '230 AW',
      'Battery': 'Up to 60 min',
      'Bin Volume': '0.76L',
      'Weight': '3.1 kg',
    },
    features: [
      'Laser reveals microscopic dust',
      'Piezo sensor counts particles',
      'LCD screen with run time',
      'HEPA filtration',
    ],
    tags: ['premium'],
    createdAt: '2024-01-12T10:00:00Z',
    updatedAt: '2024-01-22T10:00:00Z',
  },
  {
    id: 'prod-7',
    name: 'Levi\'s 511 Slim Fit Jeans - Dark Indigo',
    slug: 'levis-511-slim-fit-jeans',
    description: 'Classic slim fit jeans with stretch for comfort. Perfect for everyday wear.',
    price: 3499,
    originalPrice: 4999,
    discount: 30,
    images: [
      'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600',
    ],
    category: 'Fashion',
    subcategory: 'Men',
    brand: "Levi's",
    rating: 4.4,
    reviewCount: 4532,
    stock: 234,
    specifications: {
      'Fit': 'Slim',
      'Rise': 'Mid-rise',
      'Material': '99% Cotton, 1% Elastane',
      'Wash': 'Dark indigo',
    },
    features: [
      'Stretch denim',
      'Slim through hip and thigh',
      '5-pocket styling',
      'Button fly',
    ],
    tags: ['bestseller', 'sale'],
    createdAt: '2024-01-03T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'prod-8',
    name: 'boAt Airdopes 141 TWS Earbuds',
    slug: 'boat-airdopes-141',
    description: 'True wireless earbuds with powerful bass, 42H playback, and IPX4 water resistance.',
    price: 1299,
    originalPrice: 2990,
    discount: 57,
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600',
    ],
    category: 'Electronics',
    subcategory: 'Accessories',
    brand: 'boAt',
    rating: 4.2,
    reviewCount: 12453,
    stock: 567,
    specifications: {
      'Driver': '8mm',
      'Battery': '42H total playback',
      'Connectivity': 'Bluetooth 5.1',
      'Water Resistance': 'IPX4',
    },
    features: [
      'BEAST Mode for gaming',
      'ENx technology',
      'Touch controls',
      'Voice assistant support',
    ],
    tags: ['bestseller', 'deal'],
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'prod-9',
    name: 'Prestige Iris Plus 750W Mixer Grinder',
    slug: 'prestige-iris-plus-mixer',
    description: 'Powerful 750W mixer grinder with 4 jars for all your kitchen needs.',
    price: 3999,
    originalPrice: 5495,
    discount: 27,
    images: [
      'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=600',
    ],
    category: 'Home & Kitchen',
    subcategory: 'Kitchen Appliances',
    brand: 'Prestige',
    rating: 4.3,
    reviewCount: 8765,
    stock: 178,
    specifications: {
      'Power': '750W',
      'Jars': '4 (Wet, Dry, Chutney, Juicer)',
      'Speed': '3 Speed + Pulse',
      'Warranty': '2 Years',
    },
    features: [
      'Stainless steel blades',
      'Anti-skid feet',
      'Flow breakers for fine grinding',
      'Overload protection',
    ],
    tags: ['deal'],
    createdAt: '2024-01-06T10:00:00Z',
    updatedAt: '2024-01-16T10:00:00Z',
  },
  {
    id: 'prod-10',
    name: 'OnePlus 12 256GB - Flowy Emerald',
    slug: 'oneplus-12-256gb',
    description: 'Flagship killer with Snapdragon 8 Gen 3, Hasselblad camera, and 100W fast charging.',
    price: 64999,
    originalPrice: 69999,
    discount: 7,
    images: [
      'https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=600',
    ],
    category: 'Electronics',
    subcategory: 'Smartphones',
    brand: 'OnePlus',
    rating: 4.6,
    reviewCount: 1234,
    stock: 67,
    specifications: {
      'Display': '6.82-inch 2K LTPO AMOLED',
      'Processor': 'Snapdragon 8 Gen 3',
      'RAM': '12GB',
      'Storage': '256GB',
      'Camera': '50MP + 64MP + 48MP',
      'Battery': '5400mAh',
    },
    features: [
      'Hasselblad camera system',
      '100W SUPERVOOC charging',
      '50W wireless charging',
      'Aqua Touch 2.0',
    ],
    tags: ['new', 'trending'],
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-01-25T10:00:00Z',
  },
  {
    id: 'prod-11',
    name: 'Philips Air Fryer HD9252/90',
    slug: 'philips-air-fryer-hd9252',
    description: 'Rapid Air technology fries with up to 90% less fat. 4.1L capacity for family cooking.',
    price: 7999,
    originalPrice: 12995,
    discount: 38,
    images: [
      'https://images.unsplash.com/photo-1626509653291-18d9a934b9db?w=600',
    ],
    category: 'Home & Kitchen',
    subcategory: 'Kitchen Appliances',
    brand: 'Philips',
    rating: 4.5,
    reviewCount: 5678,
    stock: 89,
    specifications: {
      'Capacity': '4.1L',
      'Power': '1400W',
      'Temperature': '80-200°C',
      'Timer': '60 min',
    },
    features: [
      'Rapid Air Technology',
      'Digital touch screen',
      '7 presets',
      'Dishwasher safe parts',
    ],
    tags: ['bestseller', 'deal'],
    createdAt: '2024-01-04T10:00:00Z',
    updatedAt: '2024-01-14T10:00:00Z',
  },
  {
    id: 'prod-12',
    name: 'Fitbit Charge 6 Fitness Tracker',
    slug: 'fitbit-charge-6',
    description: 'Advanced health and fitness tracker with Google integration, GPS, and 7-day battery.',
    price: 14999,
    originalPrice: 17999,
    discount: 17,
    images: [
      'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600',
    ],
    category: 'Sports & Fitness',
    subcategory: 'Fitness Trackers',
    brand: 'Fitbit',
    rating: 4.4,
    reviewCount: 2345,
    stock: 112,
    specifications: {
      'Display': 'AMOLED',
      'Battery': '7 days',
      'GPS': 'Built-in',
      'Water Resistance': '50m',
    },
    features: [
      'Google Maps & Wallet',
      'Heart rate zones',
      'Sleep tracking',
      'Stress management',
    ],
    tags: ['new'],
    createdAt: '2024-01-11T10:00:00Z',
    updatedAt: '2024-01-21T10:00:00Z',
  },
]

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@email.com',
    phone: '+91 98765 43210',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100',
    addresses: [
      {
        id: 'addr-1',
        name: 'Rahul Sharma',
        phone: '+91 98765 43210',
        addressLine1: '42, Sunrise Apartments',
        addressLine2: 'Sector 15',
        landmark: 'Near Metro Station',
        city: 'Noida',
        state: 'Uttar Pradesh',
        pincode: '201301',
        isDefault: true,
        type: 'home',
      },
      {
        id: 'addr-2',
        name: 'Rahul Sharma',
        phone: '+91 98765 43210',
        addressLine1: 'Tech Park Tower B, 5th Floor',
        addressLine2: 'Whitefield',
        city: 'Bangalore',
        state: 'Karnataka',
        pincode: '560066',
        isDefault: false,
        type: 'work',
      },
    ],
    role: 'user',
    createdAt: '2023-06-15T10:00:00Z',
  },
]

// Mock Orders
export const mockOrders: Order[] = [
  {
    id: 'order-1',
    orderNumber: 'ORD-2024-001234',
    userId: 'user-1',
    items: [
      { product: products[0], quantity: 1, price: 159900 },
      { product: products[3], quantity: 1, price: 29990 },
    ],
    shippingAddress: mockUsers[0].addresses[0],
    billingAddress: mockUsers[0].addresses[0],
    paymentMethod: 'upi',
    paymentStatus: 'paid',
    orderStatus: 'delivered',
    subtotal: 189890,
    gst: 34180,
    deliveryCharge: 0,
    discount: 5000,
    total: 219070,
    couponCode: 'SAVE5K',
    trackingNumber: 'TRK123456789',
    estimatedDelivery: '2024-01-28',
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-01-28T15:00:00Z',
  },
  {
    id: 'order-2',
    orderNumber: 'ORD-2024-001235',
    userId: 'user-1',
    items: [
      { product: products[4], quantity: 2, price: 13995 },
    ],
    shippingAddress: mockUsers[0].addresses[0],
    billingAddress: mockUsers[0].addresses[0],
    paymentMethod: 'cod',
    paymentStatus: 'pending',
    orderStatus: 'shipped',
    subtotal: 27990,
    gst: 5038,
    deliveryCharge: 49,
    discount: 0,
    total: 33077,
    couponCode: null,
    trackingNumber: 'TRK987654321',
    estimatedDelivery: '2024-02-05',
    createdAt: '2024-02-01T10:00:00Z',
    updatedAt: '2024-02-03T10:00:00Z',
  },
]

// Mock Reviews
export const mockReviews: Review[] = [
  {
    id: 'review-1',
    userId: 'user-1',
    userName: 'Rahul S.',
    productId: 'prod-1',
    rating: 5,
    title: 'Best iPhone Ever!',
    comment: 'The camera quality is phenomenal and the titanium build feels premium. Battery life has improved significantly from my old iPhone 13.',
    helpful: 234,
    verified: true,
    createdAt: '2024-01-25T10:00:00Z',
  },
  {
    id: 'review-2',
    userId: 'user-2',
    userName: 'Priya M.',
    productId: 'prod-1',
    rating: 4,
    title: 'Great but expensive',
    comment: 'Amazing phone with great features. Only complaint is the price, but you get what you pay for.',
    helpful: 156,
    verified: true,
    createdAt: '2024-01-22T10:00:00Z',
  },
]

// Mock Coupons
export const mockCoupons: Coupon[] = [
  {
    code: 'WELCOME10',
    type: 'percentage',
    value: 10,
    minPurchase: 1000,
    maxDiscount: 500,
    validFrom: '2024-01-01',
    validTo: '2024-12-31',
    usageLimit: 1000,
    usedCount: 234,
  },
  {
    code: 'SAVE5K',
    type: 'fixed',
    value: 5000,
    minPurchase: 50000,
    validFrom: '2024-01-01',
    validTo: '2024-03-31',
    usageLimit: 500,
    usedCount: 123,
  },
  {
    code: 'FLAT20',
    type: 'percentage',
    value: 20,
    minPurchase: 2000,
    maxDiscount: 1000,
    validFrom: '2024-01-01',
    validTo: '2024-02-29',
    usageLimit: 2000,
    usedCount: 1567,
  },
]

// Dashboard Stats
export const dashboardStats: DashboardStats = {
  totalOrders: 15234,
  totalRevenue: 45678900,
  totalProducts: 1234,
  totalUsers: 8765,
  ordersToday: 156,
  revenueToday: 2345600,
  pendingOrders: 89,
  lowStockProducts: 23,
}

// Indian States for address
export const indianStates = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka',
  'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
  'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
  'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
  'Delhi', 'Jammu and Kashmir', 'Ladakh', 'Puducherry', 'Chandigarh',
]

// Banks for Net Banking
export const banks = [
  { id: 'sbi', name: 'State Bank of India', logo: 'SBI' },
  { id: 'hdfc', name: 'HDFC Bank', logo: 'HDFC' },
  { id: 'icici', name: 'ICICI Bank', logo: 'ICICI' },
  { id: 'axis', name: 'Axis Bank', logo: 'AXIS' },
  { id: 'kotak', name: 'Kotak Mahindra Bank', logo: 'KOTAK' },
  { id: 'pnb', name: 'Punjab National Bank', logo: 'PNB' },
  { id: 'bob', name: 'Bank of Baroda', logo: 'BOB' },
  { id: 'canara', name: 'Canara Bank', logo: 'CANARA' },
]

// UPI Apps
export const upiApps = [
  { id: 'gpay', name: 'Google Pay', color: '#4285F4' },
  { id: 'phonepe', name: 'PhonePe', color: '#5F259F' },
  { id: 'paytm', name: 'Paytm', color: '#00BAF2' },
  { id: 'amazonpay', name: 'Amazon Pay', color: '#FF9900' },
  { id: 'bhim', name: 'BHIM', color: '#00B862' },
]
